# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: Install Node.js

- script: npm ci
  displayName: Install dependencies

- script: npm test
  displayName: Run tests

- script: npm run deploy
  displayName: Deploy to AWS
  env:
    JWT_SECRET: $(jwt.secret)
    HONEYCOMB_WRITE_KEY: $(honeycomb.write_key)
    AWS_DEFAULT_REGION: $(aws.region)
    AWS_ACCESS_KEY_ID: $(aws.accessKeyId)
    AWS_SECRET_ACCESS_KEY: $(aws.secretAccessKey)
