service:
  name: serverless-blog

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  runtime: nodejs8.10
  apiName: serverless-blog
  memorySize: 256
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:us-east-1:*:*"
  - Effect: Allow
    Action:
      - s3:Put*
      - s3:Get*
    Resource: "arn:aws:s3:::*"
  environment:
    DYNAMODB_TABLE: sls-blog-${self:provider.stage}

package:
  individually: true

functions:
  create-post:
    handler: src/functions/createPost.handle
    events:
      - http:
          method: post
          path: posts
  generate-site:
    handler: src/functions/generateSite.handle
    events:
      - http:
          method: post
          path: generate
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - blogTable
              - StreamArn
  micropub-get:
    handler: src/functions/micropub.get
    events:
      - http:
          method: get
          path: micropub
  micropub-post:
    handler: src/functions/micropub.post
    events:
      - http:
          method: post
          path: micropub
          authorizer:
            type: TOKEN
            name: micropub-verify
            identitySource: method.request.header.Authorization
  micropub-verify:
    handler: src/functions/micropub.verify

resources:
  Resources:
    blogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sls-blog-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: blogId
            AttributeType: S
          - AttributeName: path
            AttributeType: S
          - AttributeName: publishedAt
            AttributeType: S
        KeySchema:
          - AttributeName: blogId
            KeyType: HASH
          - AttributeName: path
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
        LocalSecondaryIndexes:
          - IndexName: published-posts
            KeySchema:
              - AttributeName: blogId
                KeyType: HASH
              - AttributeName: publishedAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: KEYS_ONLY
