service:
  name: serverless-blog

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-apigwy-binary

custom:
  tableName: sls-blog-${self:provider.stage}
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  runtime: nodejs8.10
  apiName: serverless-blog
  memorySize: 256
  apiKeys:
  - sls-blog-${self:provider.stage}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:us-east-1:*:*"
  - Effect: Allow
    Action:
      - sqs:ChangeMessageVisibility
      - sqs:DeleteMessage
      - sqs:GetQueueAttributes
      - sqs:ReceiveMessage
      - sqs:SendMessage
    Resource: "arn:aws:sqs:us-east-1:*:*"
  - Effect: Allow
    Action:
      - s3:Put*
      - s3:Get*
    Resource: "arn:aws:s3:::*"
  - Effect: Allow
    Action:
      - ses:SendTemplatedEmail
    Resource: "arn:aws:ses:us-east-1:*:*"
  environment:
    HONEYCOMB_WRITE_KEY: ${env:HONEYCOMB_WRITE_KEY}
    JWT_SECRET: ${env:JWT_SECRET}
    DYNAMODB_TABLE: ${self:custom.tableName}
    QUEUE_URL:
      Ref: eventQueue

functions:
  generate-site:
    handler: src/functions/generateSite.handleHttp
    timeout: 15
    events:
      - http:
          method: post
          path: generate
          private: true
  db-events:
    handler: src/functions/event.dbTrigger
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - blogTable
              - StreamArn
  queue-events:
    handler: src/functions/event.queueTrigger
    timeout: 120
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - eventQueue
              - Arn
  micropub-discover:
    handler: src/functions/discover.handle
    events:
      - http:
          method: post
          path: discover
          cors: true
  micropub-get:
    handler: src/functions/micropub.get
    events:
      - http:
          method: get
          path: micropub
          cors: true
          authorizer: &authorizer
            type: TOKEN
            name: micropub-verify
            identitySource: method.request.header.Authorization
  micropub-post:
    handler: src/functions/micropub.post
    events:
      - http:
          method: post
          path: micropub
          cors: true
          authorizer: *authorizer
  micropub-verify:
    handler: src/functions/micropub.verify
  upload-media:
    handler: src/functions/uploadMedia.handle
    events:
      - http:
          method: post
          path: micropub/media
          cors: true
          contentHandling: CONVERT_TO_BINARY
          authorizer: *authorizer
  create-token:
    handler: src/functions/token.create
    events:
      - http:
          method: post
          path: token
          cors: true
  all-pages:
    handler: src/functions/page.all
    events:
      - http:
          method: get
          path: pages
          cors: true
          authorizer: *authorizer
  get-page:
    handler: src/functions/page.get
    events:
      - http:
          method: get
          path: pages/{path+}
          cors: true
          authorizer: *authorizer
  update-page:
    handler: src/functions/page.update
    events:
      - http:
          method: put
          path: pages/{path+}
          cors: true
          authorizer: *authorizer
  delete-page:
    handler: src/functions/page.remove
    events:
      - http:
          method: delete
          path: pages/{path+}
          cors: true
          authorizer: *authorizer
  webmention:
    handler: src/functions/webmention.receive
    events:
      - http:
          method: post
          path: webmention

resources:
  Resources:
    blogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: blogId
            AttributeType: S
          - AttributeName: path
            AttributeType: S
          - AttributeName: published
            AttributeType: S
        KeySchema:
          - AttributeName: blogId
            KeyType: HASH
          - AttributeName: path
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
        LocalSecondaryIndexes:
          - IndexName: published-posts
            KeySchema:
              - AttributeName: blogId
                KeyType: HASH
              - AttributeName: published
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    eventQueue:
      Type: AWS::SQS::Queue
      Properties:
        VisibilityTimeout: 150
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - deadLetterQueue
              - Arn
          maxReceiveCount: 5

    deadLetterQueue:
      Type: AWS::SQS::Queue
      Properties: {}

    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi

    newMentionTemplate:
      Type: AWS::SES::Template
      Properties:
        Template:
          TemplateName: newMention
          SubjectPart: "{{mentionAuthor}} mentioned one of your posts"
          HtmlPart: |
            <p>Your post <a href="{{postUrl}}">&quot;{{postName}}&quot;</a> has a new mention.</p>
          TextPart: |
            Your post "{{postName}}" has a new mention.

              {{postUrl}}
